version: '3'

services:
  nginx:
    image: deshanmadk/3cs-nginx:v1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - uptime-app

  uptime-app:
    image: deshanmadk/deshan-dev3cs
    ports:
      - 3000:3000